### ISSUE TITLE
No package 'libhackrf' found

### ISSUE THREAD

**Issue by redwards510** [scateu/kalibrate-hackrf#4]
I was following this guide https://z4ziggy.wordpress.com/2015/05/17/sniffing-gsm-traffic-with-hackrf/ but I ran into some trouble once I got to the kalibrate-hackrf part. I had already run 
`apt-get install libhackrf0 libhackrf-dev`
so I am very confused by this error:
`checking for LIBHACKRF... no configure: error: Package requirements (libhackrf) were not met:
No package 'libhackrf' found`

Do you have any ideas why that would happen? I'm on Kubuntu 15. Thank you.

**Comment by redwards510** [comment]
I used PyBombs[1] to install gnuradio (instead of packages) and was able to build kalibrate successfully. 

[1] http://pybombs.info/

**Comment by mckinnley** [comment]
I am trying to install on a Raspberry Pi 3 and getting the issue above. Any idea why it can't find llibhackrf?
